//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketETicaret
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketETicaretDBEntities : DbContext
    {
        public MarketETicaretDBEntities()
            : base("name=MarketETicaretDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler> Adminler { get; set; }
        public virtual DbSet<Adresler> Adresler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<OdemeYontemleri> OdemeYontemleri { get; set; }
        public virtual DbSet<Sepetler> Sepetler { get; set; }
        public virtual DbSet<SepetUrunleri> SepetUrunleri { get; set; }
        public virtual DbSet<SiparisDetaylari> SiparisDetaylari { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Hakkimizda> Hakkimizda { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
    }
}
