//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int OdemeID { get; set; }
        public int SiparisID { get; set; }
        public int OdemeYontemiID { get; set; }
        public string OdemeDurumu { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
    
        public virtual OdemeYontemleri OdemeYontemleri { get; set; }
        public virtual Siparisler Siparisler { get; set; }
    }
}
