//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetUrunleri
    {
        public int SepetUrunID { get; set; }
        public int SepetID { get; set; }
        public int UrunID { get; set; }
        public int Adet { get; set; }
    
        public virtual Sepetler Sepetler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
